server:
  port: 8081

spring:
  application:
    name: ms-users
  security:
    oauth2:
      resource-server:
          jwt:
            issuer-uri: http://localhost:8080/realms/parcial
      client:
        registration:
          keycloak:
            client-id: users-client
            client-secret: BYOBiiaCnflXpmPskDJLTlqiAssHjCzH
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/parcial/protocol/openid-connect/token
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




